name: Release APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: 17
        distribution: 'temurin'

    - name: Decode Keystore
      run: |
         echo "${{ secrets.UPLOAD_KEYSTORE }}" | base64 -d > release.keystore
         keytool -list -keystore release.keystore -storepass "${{ secrets.KEYSTORE_PASSWORD }}"

    - name: Verify Keystore
      run: |
         file release.keystore
         ls -lh release.keystore

    - name: Build Release APK
      env:
        KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
        KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
        KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }} 
      run: ./gradlew assembleRelease

    - name: Upload APK Artifact
      uses: actions/upload-artifact@v4
      with:
        name: quickse-apk
        path: app/build/outputs/apk/release/*.apk
